### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by cyouh95** [Jim412/sql-scratch-capstone-turn-in#1]
### Criteria 1: Report
* _Score Level:_ 4 (Exceeds Expectations)
* _Comment(s):_ Excellent job presenting your query results and thoroughly addressing each question! 
 
### Criteria 2: Query Accuracy
* _Score Level:_ 4 (Exceeds Expectations)
* _Comment(s):_ All queries accurately retrieve the data as intended.
 
### Criteria 3: Query Formatting
* _Score Level:_ 4 (Exceeds Expectations)
* _Comment(s):_ Overall great job on the formatting! Though one additional thing the [style guide](https://s3.amazonaws.com/codecademy-content/programs/learn-sql-from-scratch/SQL+Style+Guide+for+Learn+SQL+from+Scratch.pdf) recommends is to refer to columns by their col number in `GROUP BY` clauses [[x](https://github.com/Jim412/sql-scratch-capstone-turn-in/blob/afab127111d78066e1ba2c57157ed0d38bef102d/Hillmar_Codeacademy_SQL/code.sql.rtf#L68)]

### Criteria 4: Understanding underlying concepts and terminology
* _Score Level:_ 4 (Exceeds Expectations)
* _Comment(s):_ Report demonstrates clear understanding​ of churn rates.
 
 ### Overall Score: 16/16
 
Excellent job on this project! You definitely have a solid understanding of churn rates as well as good grasp on all the SQL commands. This was a long query to write, but you did a great job and obtained the correct results! 

One small tip for next time is to use a plain text editor when saving your `.sql` file. Some editors (e.g. `TextEdit`) save files with a [.rtf](https://github.com/Jim412/sql-scratch-capstone-turn-in/blob/afab127111d78066e1ba2c57157ed0d38bef102d/Hillmar_Codeacademy_SQL/code.sql.rtf) extension (which contains extra formatting info). [Here](https://www.codecademy.com/articles/text-editors-sublime-atom)'s some good suggestions for text editor you could use instead!

Your presentation slides were also very well put together! Bonus points for incorporating some graphs to help visualize the data and convey the results!

As a further challenge, continue exploring different SQL commands and test writing queries using this dataset. Have fun! :)

**Comment by Jim412** [comment]
Thank you, cyouh95.  I'll check out those plain text editors.
